backend:
  name: github
  repo: "AntonioSala/EVENTI"  # Sostituisci con il tuo nome utente e repository GitHub
  branch: main  # Usa il nome del tuo branch principale
media_folder: "src/assets/uploads"
public_folder: "/assets/uploads"
collections:
  - name: "events"
    label: "Eventi"
    folder: "src/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titolo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Descrizione", name: "description", widget: "text" }
      - { label: "Immagine", name: "image", widget: "image" }
